### ISSUE TITLE
Add bios to project

### ISSUE THREAD

**Issue by hubyeti** [apcspecialist/github-for-developers-7#3]
We should all create great bios in this project. Make sure your bio includes:

```
     - [ ] Your name
     - [ ] Where you are from
     - [ ] A favorite food
     - [ ] A hobby
```

**Comment by apcspecialist** [comment]
#3 A Clear understanding of Git and Github
- [x] David Schneider
- [x] Oldsmar, Florida
- [x] My favorite food is Pizza
- [x] My hobby is Electronics and Computer
